/*
	Working example of generalized query elsewhere in folder - needed to hunt down hardcoded references to years.
*/

SELECT DISTINCT REP_ALL_MAPPINGS.SUBJECT_AREA
		, REP_ALL_MAPPINGS.MAPPING_NAME
		, REP_WIDGET_ATTR.ATTR_NAME
		, REP_WIDGET_ATTR.ATTR_VALUE
FROM PC_REPO.REP_WIDGET_ATTR
	, PC_REPO.REP_WIDGET_INST
	, PC_REPO.REP_ALL_MAPPINGS
WHERE REP_WIDGET_ATTR.WIDGET_ID = REP_WIDGET_INST.WIDGET_ID
AND REP_WIDGET_INST.MAPPING_ID = REP_ALL_MAPPINGS.MAPPING_ID
AND REP_WIDGET_ATTR.WIDGET_TYPE IN (3,11,4)
--and rep_all_mappings.subject_area NOT LIKE 'WRK%' --omitting working directories/branches
AND upper(REP_WIDGET_ATTR.ATTR_VALUE) LIKE '%' || 'TERM_CODE' || '%' || '''200' || '%'
ORDER BY 1,2,3;