SELECT --COUNT(DISTINCT PARENT_SUBJECT_AREA), 
DISTINCT WQ.ATTR_VALUE SOURCE_NAME , M.PARENT_SUBJECT_AREA, m.PARENT_MAPPING_NAME

FROM PC_REPO.REP_ALL_MAPPINGS M ,
(

  SELECT WI.MAPPING_ID , A.ATTR_VALUE  
  FROM PC_REPO.REP_WIDGET_INST WI , PC_REPO.REP_WIDGET_ATTR A
  WHERE WI.WIDGET_ID = A.WIDGET_ID
   AND attr_value <> '0'
   AND (WI.WIDGET_TYPE = 11)
   AND (ATTR_ID = 2 OR ATTR_ID = 31)
   AND WI.WIDGET_ID IN (
        SELECT WIDGET_ID 
          FROM PC_REPO.REP_ALL_TRANSFORMS
        )
) WQ
WHERE M.MAPPING_ID = WQ.MAPPING_ID   
--AND PARENT_SUBJECT_AREA NOT LIKE 'WRK%'--omit working directory
--and SUBJECT_AREA NOT LIKE 'WRK%'--omit working directory
AND WQ.ATTR_VALUE in (

SELECT  SOURCE_NAME FROM (

  SELECT --COUNT(DISTINCT PARENT_SUBJECT_AREA), 
  DISTINCT WQ.ATTR_VALUE SOURCE_NAME , M.PARENT_SUBJECT_AREA SUBJECT_AREA

  FROM PC_REPO.REP_ALL_MAPPINGS M ,
    (

      SELECT WI.MAPPING_ID 
      , A.ATTR_VALUE  
      FROM PC_REPO.REP_WIDGET_INST WI
      , PC_REPO.REP_WIDGET_ATTR A
      WHERE WI.WIDGET_ID = A.WIDGET_ID
        AND attr_value <> '0'
        AND (WI.WIDGET_TYPE = 11)
        AND (ATTR_ID = 2 OR ATTR_ID = 31)
        AND WI.WIDGET_ID IN (
            SELECT WIDGET_ID 
            FROM PC_REPO.REP_ALL_TRANSFORMS
            )
    ) WQ
  WHERE M.MAPPING_ID = WQ.MAPPING_ID   
  --AND PARENT_SUBJECT_AREA NOT LIKE 'WRK%' --omit working directory

  UNION

  SELECT DISTINCT SOURCE_NAME, SUBJECT_AREA
  FROM PC_REPO.REP_SRC_MAPPING
  --WHERE SUBJECT_AREA NOT LIKE 'WRK%'--omit working directory
)
WHERE SOURCE_NAME NOT IN (
       SELECT SUBSTR(INFAMAP_BULK_MAP_NAME
       , 6
       , INSTR(UPPER(INFAMAP_BULK_MAP_NAME), '_BULK') -6) SOURCE_NAME
       FROM INFAMAP_BULK_ETL 
       WHERE INFAMAP_BULK_DEPT = 'COMMON'
       )
--AND SUBJECT_AREA NOT LIKE 'WRK%'--omit working directory
GROUP BY SOURCE_NAME
HAVING COUNT(DISTINCT SUBJECT_AREA) > 1 -- how many distinct directories?
)
UNION

SELECT DISTINCT SOURCE_NAME, SUBJECT_AREA, mapping_NAME
FROM PC_REPO.REP_SRC_MAPPING
WHERE SUBJECT_AREA NOT LIKE 'WRK%'
AND SOURCE_NAME <> 'DUAL' --dual sometimes used as source; don't include
AND SOURCE_NAME IN (
  SELECT  SOURCE_NAME
  FROM (
    SELECT DISTINCT WQ.ATTR_VALUE SOURCE_NAME 
    , M.PARENT_SUBJECT_AREA SUBJECT_AREA
    FROM PC_REPO.REP_ALL_MAPPINGS M ,
    (
      SELECT WI.MAPPING_ID , A.ATTR_VALUE  
      FROM PC_REPO.REP_WIDGET_INST WI 
        , PC_REPO.REP_WIDGET_ATTR A
      WHERE WI.WIDGET_ID = A.WIDGET_ID
       AND (WI.WIDGET_TYPE = 11)
       AND (ATTR_ID = 2 OR ATTR_ID = 31)
       AND WI.WIDGET_ID IN (
            SELECT WIDGET_ID 
            FROM PC_REPO.REP_ALL_TRANSFORMS
       )) WQ
    WHERE M.MAPPING_ID = WQ.MAPPING_ID
    --AND PARENT_SUBJECT_AREA NOT LIKE 'WRK%'--omit working directory
    )

UNION

SELECT DISTINCT SOURCE_NAME, SUBJECT_AREA
FROM PC_REPO.REP_SRC_MAPPING
--WHERE SUBJECT_AREA NOT LIKE 'WRK%'--omit working directory
AND SOURCE_NAME <> '0'
AND SOURCE_NAME <> 'DUAL'
)
WHERE SOURCE_NAME NOT IN (
  SELECT SUBSTR(INFAMAP_BULK_MAP_NAME, 6, INSTR(UPPER(INFAMAP_BULK_MAP_NAME), '_BULK') -6) SOURCE_NAME
         FROM INFAMAP_BULK_ETL 
         WHERE INFAMAP_BULK_DEPT = 'COMMON'
         )
  --AND SUBJECT_AREA NOT LIKE 'WRK%'--omit working directory
  GROUP BY SOURCE_NAME
  HAVING COUNT(DISTINCT SUBJECT_AREA) > 1
)
AND SOURCE_NAME NOT LIKE '%0%'
order by 1 DESC, 2