/*
     Query developed in conjunction with J Falletti to determine performance of every run.
     Can use this or similar to log performance to control tables if views/further reporting desired.

     Informatica PC 9.6
*/

SELECT DISTINCT OPB_SUBJECT.SUBJ_NAME
, OPB_WFLOW_RUN.WORKFLOW_NAME
, OPB_TASK_INST_RUN.INSTANCE_NAME
, TRUNC(OPB_TASK_INST_RUN.START_TIME) LOAD_DATE
, TO_CHAR(OPB_TASK_INST_RUN.START_TIME,'HH24:MI.SS') SESS_START_TIME
, TO_CHAR(OPB_TASK_INST_RUN.END_TIME,'HH24:MI.SS') SESS_END_TIME
, TRUNC((OPB_TASK_INST_RUN.END_TIME - OPB_TASK_INST_RUN.START_TIME) * 1440,2) DURATION_IN_MINS
FROM   PC_REPO.OPB_SUBJECT
     , PC_REPO.OPB_TASK_INST_RUN
     , PC_REPO.OPB_WFLOW_RUN
     , PC_REPO.OPB_OBJECT_TYPE
     , PC_REPO.OPB_SESS_TASK_LOG   
WHERE
  
  OPB_SUBJECT.SUBJ_ID = OPB_TASK_INST_RUN.SUBJECT_ID
     AND OPB_WFLOW_RUN.WORKFLOW_ID = OPB_TASK_INST_RUN.WORKFLOW_ID
     AND OPB_WFLOW_RUN.WORKFLOW_RUN_ID = OPB_TASK_INST_RUN.WORKFLOW_RUN_ID
     AND OPB_TASK_INST_RUN.TASK_TYPE = OPB_OBJECT_TYPE.OBJECT_TYPE_ID
     AND OPB_OBJECT_TYPE.OBJECT_TYPE = 68
     AND OPB_WFLOW_RUN.WORKFLOW_ID = OPB_SESS_TASK_LOG.WORKFLOW_ID
     AND OPB_WFLOW_RUN.WORKFLOW_RUN_ID = OPB_SESS_TASK_LOG.WORKFLOW_RUN_ID
     AND OPB_TASK_INST_RUN.WORKLET_RUN_ID = OPB_SESS_TASK_LOG.WORKLET_RUN_ID
     AND OPB_TASK_INST_RUN.INSTANCE_ID = OPB_SESS_TASK_LOG.INSTANCE_ID
     AND TRUNC(OPB_TASK_INST_RUN.START_TIME) > sysdate-1
ORDER BY 4,5,6
