/*
	Adapted and borrowed /heavily/ from Informatica forums. 
	Particularly knowledge on DECODE() for task_type and bit_options.

	Bit_options=17 is for FAIL_PARENT_IF_TASK_FAILS, which is crucial for aborting workflows if mappings or children workflows fail.

	Used in orchestration and auditing projects.

	Informatica PC 9.6.1. 
*/
SELECT
   REPOSITORY
   , FOLDER_NAME
   , WORKFLOW_OR_WORKLET
   , TASK_TYPE
   , WORKLET_OR_SESSION
   , FAIL_PARENT_IF_TASK_FAILS
FROM
	(SELECT DISTINCT   
	OPB_REPOSIT_INFO.REPOSITORY_NAME AS REPOSITORY,
	OPB_SUBJECT.SUBJ_NAME AS FOLDER_NAME,
	OPB_TASK.TASK_NAME AS WORKFLOW_OR_WORKLET,
	DECODE(OPB_TASK_INST.TASK_TYPE,58,'COMMAND',59,'DECISION',60,'EVENT WAIT',62,'START',65,'EMAIL',66,'TIMER',67,'ASSIGNMENT',68,'SESSION',70,'WORKLET',91,'CONTROL',NULL) TASK_TYPE,
	OPB_TASK_INST.INSTANCE_NAME AS WORKLET_OR_SESSION,
	DECODE (BITAND (OPB_TASK_INST.BIT_OPTIONS, 17),17,'SELECTED','NOT SELECTED') AS FAIL_PARENT_IF_TASK_FAILS
	FROM PC_REPO.OPB_TASK_INST,PC_REPO.OPB_OBJECT_TYPE,PC_REPO.OPB_TASK,
	   PC_REPO.OPB_SUBJECT, PC_REPO.OPB_REPOSIT_INFO
	WHERE OPB_TASK_INST.TASK_TYPE != 62 --we wanted to disregard Event Wait at the time
	AND OPB_TASK_INST.TASK_TYPE = OPB_OBJECT_TYPE.OBJECT_TYPE_ID
	AND OPB_TASK_INST.WORKFLOW_ID = OPB_TASK.TASK_ID
	AND OPB_TASK_INST.VERSION_NUMBER = OPB_TASK.VERSION_NUMBER
	AND OPB_TASK.SUBJECT_ID = OPB_SUBJECT.SUBJ_ID
	AND OPB_TASK.UTC_CHECKIN <> 0
	AND OPB_SUBJECT.SUBJ_NAME NOT LIKE 'WRK%'
	AND OPB_SUBJECT.SUBJ_NAME NOT LIKE 'old%'
	)
WHERE FAIL_PARENT_IF_TASK_FAILS <> 'SELECTED'


order by 1,2