/*
	Swiss army/spaghetti query for returning all pertinent information in this hierarchy:
	Folder-->workflow-->mapping-->session-->MAPPLET.

	Adapted from Informatica PC forums; used in Powercenter 9.6.1
*/

SELECT * FROM 
(	SELECT DISTINCT 
		(SELECT F.SUBJ_NAME 
		 FROM PC_REPO.OPB_SUBJECT F 
		 WHERE F.SUBJ_ID = S.SUBJECT_ID 
		) FOLDER_NAME 
	,   (SELECT WF.TASK_NAME 
		FROM PC_REPO.OPB_TASK WF, 
		PC_REPO.OPB_TASK_INST WF_INST 
		WHERE WF.TASK_ID = WF_INST.WORKFLOW_ID 
		AND WF_INST.TASK_ID = S.TASK_ID 
		) WORKFLOW_NAME
	, 	M.MAPPING_NAME MAPPING_NAME
	, 	S.TASK_NAME SESS_NAME
	,   (SELECT DECODE(OPB_SWIDGET_INST.MAPPLET_MAP_ID, 0, 'NO MAPPLET', MPLT.MAPPING_NAME ) MAPPLET_NAME 
		FROM PC_REPO.OPB_MAPPING MPLT 
		WHERE OPB_SWIDGET_INST.MAPPLET_MAP_ID = MPLT.MAPPING_ID 
		) MAPPLET_NAME 
FROM PC_REPO.OPB_SWIDGET_INST
	, PC_REPO.OPB_TASK S
	, PC_REPO.OPB_MAPPING M 
WHERE OPB_SWIDGET_INST.SESSION_ID = S.TASK_ID
AND OPB_SWIDGET_INST.MAPPING_ID = M.MAPPING_ID 
--AND S.TASK_NAME = 'YOUR_SESSION_NAME'
)
--WHERE FOLDER_NAME NOT LIKE '%/%'
--AND UPPER(MAPPING_NAME) LIKE '%%'
--AND WORKFLOW_NAME LIKE '%%'
--AND SESS_NAME LIKE '%%'